var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                  xxx           ",
   "                                                   xx      xx    xx:xx          ",
   "                                    : :      xx                  x:::x          ",
   "                                                                 xx:xx          ",
   "                                   xxxxx                          x x           ",
   "                                                                            xx  ",
   "  xx                                      : :                                x  ",
   "  x                     :                                                    x  ",
   "  x                                      xxxxx                             : x  ",
   "  x          xxxx       :                                                    x  ",
   "  x  @       x  x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxxxxxxxx  ",
   "                              x   x                  x     x                    ",
   "                              x:::x                  x:::::x                    ",
   "                              x:::x                  x:::::x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                      x::x                        xxxxxxx                                    x:x  ",
   "                                      x::x                     xxxx     xxxx                                 x:x  ",
   "                                      x::xxxxxxxxxx           xx           xx                                x:x  ",
   "                                      xx::::::::::xx         xx             xx                               x:x  ",
   "                                       xxxxxxxxxx::x         x                                    :   :   :  x:x  ",
   "                                                xx:x         x     :   :                                    xx:x  ",
   "                                                 x:x         x                                xxxxxxxxxxxxxxx::x  ",
   "                                                 x x         x     x   x                        ::::::::::::::xx  ",
   "                                                             xx   :    :    xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx:::::::::::xx                                     ",
   "                                                               xxxx:::::xxxx                                      ",
   "                                               x     x            xxxxxxx        xxx         xxx                  ",
   "                                               x     x                           x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      :  :     x   x         x         x                    ",
   "               xxxxxxx        xxx   xxx        x     x               x   x         x         x                    ",
   "              xx     xx         x   x          x     x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx       xx        x : x          x    xx               x   x   x               x                    ",
   "     @       x         x        x   x          x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x     x               x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx : xx         x     x               x     :     x x         x                    ",
   "::::x x::::::x         x::::::xx     xx::::::::xx    x::::::::::     x           x x         x                    ",
   "::::x x::::::x         x:::::xx       xxxxxxxxxx     x:::::::xx:     xxxxxxxxxxxxx xx  : :  xx                    ",
   "::::x x::::::x         x:::::x    :                 xx::::::xx :                    xx     xx                     ",
   "::::x x::::::x         x:::::x                     xx::::::xx  :                     xxxxxxx                      ",
   "::::x x::::::x         x:::::xx       xxxxxxxxxxxxxx::::::xx   :                                                  ",
   "::::x x::::::x         x::::::xxxxxxxxx::::::::::::::::::xx    :                                                  ",
   "::::x x::::::x         x::::::::::::::::::::::::::::::::xx     :                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        :                                                                     ",
   "                                                                                                              ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                        x                                                                     ",
   "                                       xxx                                                                    ",
   "                                       x x                 :::        :::  xxx                                ",
   "                                       x x                 :x:        :x:                                     ",
   "                                     xxx xxx                x          x                                      ",
   "                                      x   x                 x   ::::   x       xxx                            ",
   "                                      x   x                 x          x      x:::x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                                      x   xxxxxxxxx   xxxxxxxx              x x                               ",
   "                                      x   x           x                    x:::x                              ",
   "                                      x   x           x                     xxx                               ",
   "                                     xx   xx          x                                                       ",
   "                                      x   x           x            xxx                                        ",
   "                                      x   x           x           x:::x                                       ",
   "                                      x   x           x     :      xxx       xxx                              ",
   "                                     xx   xx          x                     x:::x                             ",
   "                              :   :   x   x           x     x                xx         xxx                   ",
   "                                      x   x           x              x                 x:::x                  ",
   "                             xxx xxx xxx xxx     : :  x::::::::::::::x                    x                   ",
   "                             x xxx x x xxx x          x::::::::::::::x                                        ",
   "                             x             x   xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                         x     x     x                                         x:::x                xxx  ",
   "  x x                         x    xxx    x                                          xxx                 x x  ",
   "  x                           x    xxx    xxxxxxx                        xxxxx                             x  ",
   "  x                           x           x                              x   x                             x  ",
   "  x                           xx          x                              x x x                             x  ",
   "  x                                       x        :xxxx :     :xxxx :     xxx xxx                         x  ",
   "  x                xxx             : :    x                              x         xxx                     x  ",
   "  x               xxxxx       xx          x                             xxx       x:::x          x         x  ",
   "  x               :xxx:       x    xxx    x                             x x        xxx          xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x :: x    x :: x    x ::  xx xx                    xxx        x  ",
   "  x      @          x         x           x::x    x::::x    x::::x    xx   xx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          :                                                                       x x x       ",
   "                                                                                             : : :xxx x       ",
   "                   xxx                                                                                x       ",
   "       :  :  :                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x  :  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       :  :  :            :                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          :              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          :                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                  : :                                         ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x : xxxxxxxxx : xxxxxxxxx : xx                                                x                   ",
   "  x         x   x       x   x       x   x                  : :                  x     x                       ",
   "  x  @      xxxxx   :   xxxxx   :   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x                                     x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x:::::::::::::::::::::xxx:::::::::::::::::::::::::::::::::::",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];
